### PR TITLE
Fix SSL_shutdown() logic

### PR DESCRIPTION
**Pull request by wongsyrone**
The manpage suggests `SSL_shutdown()` should be invoked in two stages, calling it the first one result in unidirectional TLS termination, a.k.a. sending close notify to the peer, most time should be okay, but TLS 1.3 requires we do bidirectional TLS termination, we should call SSL_shutdown() the second time to wait for peer's close notify, the corresponding 1.1.1 manpage suggests users using SSL_read() to do so, we just retry SSL_shutdown() and evaluate the returning value.

### CODE REVIEW

**Comment by wongsyrone** [comment]
The bug is discovered via SSL_CTX_set_info_callback(), it has been sent as PR in https://github.com/sfackler/rust-openssl/pull/1460 using the posted example code in that PR.

before:
```
SSL3 alert read:warning:close notify
```

after:
```
SSL3 alert read:warning:close notify
SSL3 alert write:warning:close notify
```

Please note the read and write part.

**Comment by sfackler** [comment]
I think you may be looking at an older draft of the TLS 1.3 spec - full bidirectional shutdown used to be required, but that was removed. Here's what the published standard says:

>    Each party MUST send a "close_notify" alert before closing its write
>    side of the connection, unless it has already sent some error alert.
>    This does not have any effect on its read side of the connection.
>    Note that this is a change from versions of TLS prior to TLS 1.3 in
>    which implementations were required to react to a "close_notify" by
>    discarding pending writes and sending an immediate "close_notify"
>    alert of their own.  That previous requirement could cause truncation
>    in the read side.  Both parties need not wait to receive a
>    "close_notify" alert before closing their read side of the
>    connection, though doing so would introduce the possibility of
>    truncation.

https://tools.ietf.org/html/rfc8446#section-6.1

Unconditionally performing a bidirectional shutdown can cause the shutdown process to "hang" when the peer does not behave well, so implementations generally just fire off a close_notify as a best-effort and then close the socket.

I'd be happy to add a `poll_ssl_shutdown` (or whatever name) method that returned the `ShutdownResult` to allow code to perform a full shutdown if it wanted though!

**Comment by wongsyrone** [comment]
Just as you quoted, Both parties need not wait to receive a
"close_notify" alert before closing their read side of the
connection, **though doing so would introduce the possibility of
truncation**. 

It possibly introduces vulnerability on truncation as unidirectional shutdown works like socket shutdown(Write), the channel is partially closed and can still receive data until peer's "close notify" is arrived or the underlying socket is closed.

I think most implementation just do uni-directional SSL_shutdown() and close the underlying socket, which doesn't have the truncation vulnerability.

Here is my reference:
C++ Boost.Asio impl: https://github.com/boostorg/asio/blob/develop/include/boost/asio/ssl/detail/impl/engine.ipp#L324

**Comment by wongsyrone** [comment]
Another ref:

When I was searching, I got https://stackoverflow.com/questions/28056056/handling-ssl-shutdown-correctly, someone points me to https://github.com/openssl/openssl/issues/7948, then I got https://wiki.openssl.org/index.php/TLS1.3#Sessions

> Calling SSL_get1_session() after a 2 way shutdown will give a resumable session if any was sent.
> If the server sends session tickets and you want to be able to get a resumable session, you need to either call SSL_read() after the ticket was sent or do a 2 way shutdown.

Please note the `2 way shutdown`

**Comment by wongsyrone** [comment]
Close due to no response.

**Comment by sfackler** [comment]
Apologies for not responding immediately, but Github is not my full time job.

You are correct that a 1-way shutdown introduces the possibility of data truncation, but the majority of protocols in the modern era maintain their own framing and don't rely on the transport level EOF for any important signaling.

This shutdown method is defined on the `AsyncWrite` trait, and is supposed to behave like shutting down the write side of the pipe as far as I know. As I mentioned above, I would be happy to add a method that more directly exposes the SSL_shutdown interface for consumers that want to perform a full 2-way shutdown.

**Comment by wongsyrone** [comment]
> This shutdown method is defined on the `AsyncWrite` trait, and is supposed to behave like shutting down the write side of the pipe as far as I know.

If I understand it correctly, futures-rs try to make poll_shutdown() and poll_close() as synonyms

ref:
https://github.com/rust-lang/futures-rs/blob/master/futures-util/src/compat/compat01as03.rs#L458
https://github.com/rust-lang/futures-rs/blob/master/futures-util/src/compat/compat03as01.rs#L272

**Comment by wongsyrone** [comment]
`tokio_io` becomes `tokio::io` eventually.

**Pull request closed without merging**
